apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_HOST: "{{ .Values.config.DATABASE_HOST }}"
  DATABASE_PORT: "{{ .Values.config.DATABASE_PORT }}"
  DATABASE_NAME: "{{ .Values.config.DATABASE_NAME }}"
  DATABASE_USER: "{{ .Values.config.DATABASE_USER }}"
  DATABASE_PASSWORD: "{{ .Values.config.DATABASE_PASSWORD }}"
  JWT_SECRET: "{{ .Values.config.JWT_SECRET }}"
  YAGPT_KEY: "{{ .Values.config.YAGPT_KEY }}"
  YAGPT_FOLDER: "{{ .Values.config.YAGPT_FOLDER }}"